### PR TITLE
Issue 7 migrate cli from reso certification

### PR DESCRIPTION
**Pull request by michaelpede**
The esLint issues are also fixed with this.

### CODE REVIEW

**Comment by michaelpede** [comment]
This solves two issues on this repro.  Issue #7 and Issue #5

**Comment by darnjo** [comment]
> This solves two issues on this repro. Issue #7 and Issue #5

This should be part of the issue description rather than a separate comment in the future and there should be a brief summary about what the issues were about. 

In the esLint case, this is more of a tweak than fixing what was already there. We just decided to turn one of the options off on this repo since we won't ever React components in it.

**Comment by darnjo** [comment]
@michaelpede, pushed an update for #5 regarding `esLint` and any related issues it caught in the files in `main`. You should update from `main` at this point and re-run the linter with `esLint .`.

**Comment by darnjo** [comment]
To add, I would expect the the thing that restored from a directory to be in [this file](https://github.com/RESOStandards/reso-certification-utils/blob/main/utils/restoreCertServerFromPath.js), with references to it in `./index.js`. It would export `restore` which would take an object with a variety of parameters and be imported by `index.js`. 

Parameter checking should be done on the client side, meaning `index.js`, where appropriate with required parameters. That seems to be happening now, though I haven't checked it yet. Then the backend functions should throw errors when something critical fails, as you have done. We should perhaps talk abou serializing the last restored item upon failure (to a local disk somewhere, like in a reso-certification-utils.tmp.json or something). We can address that in a later issue.

**Comment by darnjo** [comment]
To resolve the GitGuardian issue, please move the Google Sheets API Key to the config file. This key could potentially have write access at some point in the future so we don't want it in a public repo.

**Comment by darnjo** [comment]
This isn't really done yet since we haven't merged the code.

**Comment by darnjo** [comment]
This isn't done yet since we haven't merged the code.

**Comment by darnjo** [comment]
Re-opening as this isn't done yet since the code hasn't been approved and merged. Any additional work should have been done in this branch.

**Pull request closed without merging**
