### PR TITLE
Create DockerfileBullseye

### PR DESCRIPTION
**Pull request by alifemove**
Alpine/gradle don't play nice on apple silicon

### CODE REVIEW

**Comment by darnjo** [comment]
Nice! Thanks for making a PR.

I'll give it a try and approve once I've tested a bit.

**Comment by alifemove** [comment]
runDDTests on 1.7 -a seems to be working.

I can't seem to find how to run the api server core tests though. Got a hint?

**Comment by darnjo** [comment]
The Web API Core tests use the Commander directly rather than through RESO Certification Utile. However, you should be able to call the Commander from the Docker image.

**Review by mohit-s96 — APPROVED** [review]
Builds and runs on macbook m1.

**Pull request merged**
